export const appName = '浅言'
export const PROFILE_MINE_MESSAGE = '我的消息'
export const PROFILE_MINE_FOLLOW = '我的关注'
export const PROFILE_MINE_TRASH = '我的垃圾箱'
export const PROFILE_RECOMMOND_F = '推荐给好友'
export const PROFILE_NOTIFICATION = '系统通知'
export const PROFILE_FEEDBACK = '反馈问题'
export const PROFILE_ABOUT_US = '关于我们'
